apiVersion: v1
data:
  email: dmluYXlhay5vamhhQDQ3YmlsbGlvbi5jb20=
  token: Z2hwX20wZDRLUkNpNHVKZ0tnQ3ExZUZlYjN5Uk1idkJmdjNVRDZTZw==
  user: VmluYXlhay1vamhhNDc=
kind: Secret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: workflows
